import os
import time

from dotenv import load_dotenv
from Spotify_Client_V2 import *

load_dotenv("config.env")
client_secret = os.getenv("CLIENT_SECRET")
client_id = os.getenv("CLIENT_ID")
user_id = ""
user_name = ""

print("Hello! Welcome to my Spotify API Client! I'm glad you decided to check out my program.")
user_name = input("What is you name? ")
time.sleep(1)
print('Hello,', user_name, '!')
time.sleep(1)
print("You will be redirected to a browser when you will sign into your Spotify Account and then you will be redirected to a localhost:3000 site.")
time.sleep(1)
print("Copy the full link (http://localhost:3000...); you will need it in the next steps.")
print("The program will begin shortly...")
time.sleep(5)
try:
    spotify_client = SpotifyAPI(client_id, client_secret)
except:
    print("An exception occurred. Your client id and secret are most likely incorrect.")

time.sleep(10)
url = input("Paste the full url here and press Enter: ")

while(not(url.startswith("http"))):
    url = input("Please enter the full URL: ")

try:
    spotify_client.parse_url_for_code(url)
except:
    print("the URL is incorrect. Try again")

#print("Please enter your user id: (This can be found in your spotify accounts info.)")
user_info = spotify_client.get_user_info()
user_id = user_info['id']

response = spotify_client.get_user_playlists(user_id=user_id)
spotify_client.clear_user_playlists()
user_playlists = spotify_client.list_user_playlists(response)

print("Here are your playlists. Choose one by entering the number:")

num = 1
for i in spotify_client.user_playlists:
    print(str(num) + '.', i['name'])
    num+=1

print("")
print("What playlist would you like to parse:")
playlist_num = int(input("# "))
playlist_select = user_playlists[playlist_num-1]

print("We are now going to search for the artist you would like to get from your playlist.")
time.sleep(2)
artist = input("What is the artist's name: ")
search = spotify_client.search(artist, search_type='artist')
search_list = []
for i in range(6):
    q = {'name' : search['artists']['items'][i]['name'],
        'id' : search['artists']['items'][i]['id']
        }
    search_list.append(q)
num = 1
for x in search_list:
    print(str(num) + '.',x['name'])
    num+=1
qn = input("Does your desired artist appear in the search? (y/n)")

while(qn.lower() != 'y' ):
    artist = input("What is the artist's name: ")
    search = spotify_client.search('Drake', search_type='artist')
    search_list = []
    for i in range(6):
        q = {'name' : search['artists']['items'][i]['name'],
            'id' : search['artists']['items'][i]['id']
            }
        search_list.append(q)
    num = 1
    for x in search_list:
        print(str(num) + '.', x['name'])
        num+=1
    qn = input("Does your desired artist appear in the search? (y/n)")
print("What is the artist number: ")
artist_num = int(input("#"))
while(not(artist_num in range(6))):
    artist_num = int(input("Enter a valid artist #: "))

artist_selected = search_list[artist_num-1]

print("The playlist parsing feature is in progress...")
print("")

playlist_items_response = spotify_client.get_playlist_items(playlist_id=playlist_select['id'])
spotify_client.clear_playlist_items()
rep = spotify_client.parse_playlist_items(playlist_items_response)

target_songs = []
for x in rep:
    for i in x['artists']:
        if i['id'] == artist_selected['id']:
            target_songs.append(x)
            break

#create a list of the uris of the target songs
target_songs_uri = []
for i in target_songs:
    target_songs_uri.append(i['uri'])

print("Playlist parsing complete.")
time.sleep(2)
print("Time to create the new playlist...")
time.sleep(1)
query = input("Would you like an autogenerated playlist name? (y/n): ")

new_playlist_name = ""
new_playlist_description = ""
if (query.lower() != 'y'):
    new_playlist_name = input("What is the new playlist's name: ")
    new_playlist_description = input("Description: ")
    cplay = spotify_client.create_playlist(user_id=user_id, name=new_playlist_name, description=new_playlist_description, artist=artist_selected['name'], playlist_name=playlist_select['name'])
else:
    new_playlist_description = input("What is the playlist description: ")
    cplay = spotify_client.create_playlist(user_id=user_id,description=new_playlist_description, artist=artist_selected['name'], playlist_name=playlist_select['name'])

print("Adding songs to the new playlist...")
time.sleep(2)
done = spotify_client.add_song_to_playlist(uri_list=target_songs_uri, playlist_id=cplay['id'])

print("PROCESS FINISHED.")
print("Check you Spotify library for results.")
time.sleep(1)
print("")
print("Thank you for using my software! All feedback is much appreciated!")
time.sleep(1)
print("I wish you the best!")
time.sleep(1)
print("GOODBYE!")
